### ISSUE TITLE
Running deep-cover drops into a pry session

### ISSUE THREAD

**Issue by doudou** [deep-cover/deep-cover#10]
I'm trying to run deep-cover on my gem. It dropped into a pry session, that I could track down to an anonymous splat. Can reproduce with:

~~~
bundle exec deep-cover -e 'a, b, * = test'
~~~

**Comment by marcandre** [comment]
Awesome, thanks for the great bug report.
Fixed & released

**Comment by doudou** [comment]
Thanks *so much* for deep-cover ... I was despairing about the idea of having to develop a better code coverage library myself.

**Comment by marcandre** [comment]
Thanks for the kind words 😄 
*Despair* though? You're missing out on a lot of fun! :man_dancing:
