### ISSUE TITLE
Error on `patch_rubocop`

### ISSUE THREAD

**Issue by hkdnet** [deep-cover/deep-cover#21]
## Step to reproduce

```
$ cd path/to/deep-cover
$ bundle install
$ bundle exec deep-cover .
```

## Why?

`.rubocop.yml` may contain some lines with Symbol,
https://github.com/deep-cover/deep-cover/blob/0e51084/.rubocop.yml#L106:L109
`YAML.safe_load` raises an error with them.

`Psych::DisallowedClass: Tried to load unspecified class: Symbol`

## How to fix

There seem to be some problems.
We should not use `YAML.load` on this context, right?
However, `.rubocop.yml` may contains Symbols.
And we have to patch `.rubocop.yml` to exclude `'lib/**/*'` or `'app/**/*'.`

I have no ideas to solve these problems... 😿

**Comment by marcandre** [comment]
We started from an existing `.rubocop` that @MaxLap had around, but these rules aren't actually useful, so I removed them.
Thanks!

**Comment by hkdnet** [comment]
Thanks!
But this will happen on some repository which has `.rubocop.yml` with Symbol.
Some additional option to skip patching rubocop may be needed

**Comment by marcandre** [comment]
Oh, right, indeed. Better use `load` then. We're executing the test suite, so there's no reason to worry about safety issues with the rubocop.yml...
