### ISSUE TITLE
NameError: uninitialized constant Parser::Source::TreeRewriter

### ISSUE THREAD

**Issue by almostwhitehat** [deep-cover/deep-cover#22]
In the latest release (0.3.0) I am getting the following exception:

> NameError: uninitialized constant Parser::Source::TreeRewriter
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/covered_code.rb:104:in `instrument_source'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/covered_code.rb:23:in `initialize'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/coverage/base.rb:27:in `new'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/coverage/base.rb:27:in `covered_code'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/custom_requirer.rb:135:in `cover_and_execute'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/custom_requirer.rb:104:in `require'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/core_ext/require_overrides.rb:14:in `block in require'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/core_ext/require_overrides.rb:14:in `catch'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/core_ext/require_overrides.rb:14:in `require'
  /srv/mgmt/local/config/application.rb:4:in `<top (required)>'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/core_ext/require_overrides.rb:15:in `require'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/core_ext/require_overrides.rb:15:in `require'
  /srv/mgmt/local/config/environment.rb:2:in `<top (required)>'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/core_ext/require_overrides.rb:15:in `require'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/core_ext/require_overrides.rb:15:in `require'
  /srv/mgmt/local/spec/rails_helper.rb:4:in `<top (required)>'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/core_ext/require_overrides.rb:15:in `require'
  /home/deploy/ruby/2.1.0/gems/deep-cover-0.3.0/lib/deep_cover/core_ext/require_overrides.rb:15:in `require'
  /srv/mgmt/local/spec/models/some_model_spec.rb:2:in `<top (required)>'
  /home/deploy/ruby/2.1.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
  /home/deploy/ruby/2.1.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /home/deploy/ruby/2.1.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
  /home/deploy/ruby/2.1.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /home/deploy/ruby/2.1.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
  /home/deploy/ruby/2.1.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
  /home/deploy/ruby/2.1.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  /home/deploy/ruby/2.1.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  /home/deploy/ruby/2.1.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  /home/deploy/ruby/2.1.0/bin/rspec:23:in `load'
  /home/deploy/ruby/2.1.0/bin/rspec:23:in `<top (required)>'

It looks like a few recent commits made the switch to Parser::Source::TreeRewriter, but that hasn't been released yet.

To work around this issue for now, I included the **tree_rewriter_release** branch from **marcandre/parser** in my Gemfile.

**Comment by marcandre** [comment]
Oh, I should have thought about this, but indeed, the `Gemfile` isn't taken into account when installing a gem.

TreeRewriter just got merged, so next version of Parser will be ok. I probably should have waited before releasing... Not too sure what to do now to avoid issues for others.

**Comment by almostwhitehat** [comment]
Hmmm.. might be a good idea to roll back this change and release as 0.3.1 unless the next parser release is happening soon?

**Comment by doudou** [comment]
I think this can be closed as to 0.4.0

**Comment by marcandre** [comment]
Fixed (for good) in 0.5.0
