### ISSUE TITLE
Consider splitting out CLI into separate gem

### ISSUE THREAD

**Issue by mojavelinux** [deep-cover/deep-cover#30]
I love this library because it provides much deeper coverage than what I get with Ruby / SimpleCov alone. What I don't love is that integrating it into a test suite adds a lot of dependencies to the project that aren't needed. Would you consider separating the library and the CLI into two separate gems? I think doing so would make deep-cover a lot more attractive for developers like myself who are looking to simply enhance an existing test suite to get deeper coverage insights.

These are the dependencies of the CLI to which I'm referring:

* bundler (this one seems especially unnecessary since it's meant to be a gem management tool)
* highline
* slop
* term-ansicolor
* with_progress

**Comment by marcandre** [comment]
So glad you ❤️ DeepCover, thanks for letting us know! 😄

We indeed have considered this from the very beginning and decided to wait, but the codebase is much more mature now so this would be a good thing to do soonish.

I realize that it complexifies your Gemfile.lock. Except for `slop` (which has highly conflicting versions), it should not cause any real problems, and we are already careful not to use any of these dependencies while the tests are run. But yes, expect a `deep-cover-cli` gem some time in the future (or a `deep-cover-runtime` gem?). Could even be sooner if you're up for the challenge of doing a PR for this!

**Comment by MaxLap** [comment]
I think a requirement of any spliting solution should be that `deep-cover` remain the whole complete project.  So yeah, `deep-cover-runtime` sounds better to me, since anyways, the cli is not useable without the runtime. Well see if at one point we divide into more components.

**Comment by mojavelinux** [comment]
I'd be willing to help out. In fact, I explored what it would take to pull out the CLI in [this branch](https://github.com/mojavelinux/deep-cover/tree/no-cli) in my fork. I managed to get all the tests that don't use the CLI running and it works when I use it in another project.

I know the CLI dependencies don't seem like much, but it gave me pause when I first encountered the project, which could be true for others as well.

I'm also not enamored by the integration with Bundler. It's too much magic for my taste and makes the project more difficult to use. I use RVM with gemsets and deep-cover's integration with Bundler is leading to conflicts at runtime that I can't figure out. IMO, it's better just to explain how to use Ruby properly and run the execution through normal channels.

**Comment by marcandre** [comment]
Interesting about `bundler` (I assume you are talking about `deep-cover exec`), maybe we didn't take the right design decision. In any case, there's no need to use `deep-cover exec`. You can simply call `DEEP_COVER=t rake test` or something.

**Comment by mojavelinux** [comment]
Yep, I'm referring to the deep-cover command, both `exec` and when you point it at a project (the latter which seems to clone the project and run bundler, but it's not clear what RVM / gemset it's using then).

It's good to know about the DEEP_COVER env variable. However, when I enable that, I don't get get a coverage report. I'm not sure why. Still investigating.

**Comment by mojavelinux** [comment]
Aha, I need to also require `deep-cover`.

Now I see the error I was getting when using `deep-cover exec`.

```
...
porter/html/site.rb:32:in `block in compile_stylesheet'
/home/dallen/projects/asciidoctor/kramdown-asciidoc/.bundle/gems/ruby/2.5.0/gems/deep-cover-0.5.3/lib/deep_cover/reporter/html/site.rb:32:in ``': No such file or directory - sass (Errno::ENOENT)
```

Perhaps missing a dependency.

**Comment by marcandre** [comment]
Oh, right sorry about `sass`. I opened #32.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
I just discovered the istanbul / nyc integration and I was like :heart_eyes:. (In this case, I don't mind the extra CLI dependency because it's strictly for reporting).

**Comment by MaxLap** [comment]
@mojavelinux FYI, I just released 0.5.4 which doesn't use Bundler for `deep-cover exec`, so you shouldn't need to use `DEEP_COVER=t`.

At the moment the clone mode (when exec isn't specified) does still use Bundler. You are right that it's not clear which rvm / gemset is used in that situation. My guess would be that it's the same one, I don't see how it could be different.

There are many grey zones about the clone mode at the moment..

**Comment by mojavelinux** [comment]
Nice work!

I agree the clone mode introduces some gray areas. Even if the rvm / gemset doesn't change, that may not be the desired behavior when running Bundler. Anytime you invoke `bundle` programmatically, you need to provide a way to pass parameters or load a custom config. Otherwise, you can end up littering gems into the global space.

For example, if I'm installing gems into a vendored directory (using `bundle --path`) in my project, and deep-clone switches directory and invokes `bundle` without arguments, now I'm going to end up with a ton of gems in my global gem directory (not vendored).

**Comment by MaxLap** [comment]
Very interesting. (And worrying, since it makes things quite a bit more complicated to do clone mode).

The main use of clone mode (or goal of), at the moment, is:
* for us to self cover
* for people to just try out deep-cover without having to change an code
* for gems that we depend on to be able to use deep-cover

I'll try to keep this in mind when I get to focus on the CLI and especially clone mode, and try to avoid bundler as much as possible.

**Comment by mojavelinux** [comment]
If that mode is mostly intended for internal use, then it's much less of a concern. If you simply add a `--bundle-path` argument, you can cover most of the cases of which I described. Simpler still, if you're going to run `bundle install` in a clean workspace, perhaps always just target "vendor/bundle" and you'll avoid any conflicts. After all, this is an isolated run.

**Comment by mojavelinux** [comment]
Great work @marcandre! I've already upgraded and it's working perfectly! Exactly what I was hoping for.

https://travis-ci.org/asciidoctor/kramdown-asciidoc/jobs/418543320

(In other news, I've achieved 100% coverage. A huge thanks to the deep-cover team for helping me achieve that milestone!).

**Comment by MaxLap** [comment]
Congrats on the 100%!
