### ISSUE TITLE
Is there anyway to have multiple reports when using builtin_takeover with simplecov

### ISSUE THREAD

**Issue by zs787** [deep-cover/deep-cover#54]
Hi,

I know currently there is no deep-cover support by `Codecov`, but just wondering if there is any way that I can configure `deep-cover` to have the results written in a separate file, such that I would have two files for coverage one without the branch coverage (i.e. original report generated by `SimpleCov`) and one with branch coverage (i.e. what `deep-cover` reports) while used in takeover mode with `SimpleCov`.

Thank you

**Comment by MaxLap** [comment]
I'm pretty sure you should be able to use `deep-cover report` in console after your run with takeover to get the deep-cover style report. Let me know if that's not working.

**Comment by zs787** [comment]
@MaxLap thanks for your suggestion. 
What I'm trying to do is to have two reports. Meaning can I use the takeover approach to work with our existing `SimpleCov` but need to keep the original `SimpleCov` report separate from the `deep-cover` reported results from using `deep_cover/builtin_takeover` is that possible ?

**Comment by MaxLap** [comment]
I don't think it's possible. We modify the actual code that is run. This modification could affect the results that the built-in Coverage library of Ruby generates. Are the differences from using takeover that significant?

We could look into having a way for the takeover's result to not consider the branching information, which should lead to a pretty similar (but not identical) coverage result as the builtin. This way you could then issue the report as normal.

**Comment by marcandre** [comment]
We don't actually change the line numbers of any code, so it might give reasonable results.

For example if you execute, after the takeover, something like `BuiltinCoverage.start`, then both coverage engines should be working in tandem. How you get both reports might simply be an issue of redirecting `Coverage` to `BuildinCoverage` at the right point...

I'm not entirely sure what you are trying to achieve or why so it difficult to comment further.

**Comment by zs787** [comment]
Branch coverage reporting is important to us and the main reason for us using `deep-cover`. However, to accommodate our needs and keep most of the existing setup in place we want to see if `deep-cover` when taking over can have its branch coverage results in a new report and leave the `simplecov` original report as is, such that at the end we get index.html (this is `simplecov` without `deep-cover` results) and index2.html (this would be the result of the take over process `deep-cover` + `simplecov`)

Or any other scenario that you guys know will work and can give us a good peek at our branch coverage reporting, even if we need to run `deep-cover` independently from `simplecov`, meaning in a stand alone mode to just allow us to have a look our branch coverage.

I just don't want to try things around that you guys may have already tried and tested and may know if works or not.

**Comment by zs787** [comment]
Hi guys,

I'm visiting the `deep-cover` gem again and would like make sure I understand this correctly, as after reading the thread I thought maybe things were not clear, to know if we can achieve the following, otherwise I will go ahead and close the issue if not possible.

- When using `require 'deep_cover/builtin_takeover'` along with `simplecov`  is there any way we can have the resulting `index.html` redirected to a different directory ? I know we can with `simplecov` but does `deep-cover` provide the same option ?

- If not currently possible then would it be possbile if we change it somewhere in the code without losing any of the `deep-cover` take-over functionality ?

 The reason behind this is we need to keep the original coverage `index.html` generated by `simplecov` and at the same time have another separate one for the take-over `index.html` results as we are interested in branch coverage as well but we don't want to change the original setup...etc.

**Comment by MaxLap** [comment]
Hello, `clone`, `report` and `exec` all 3 accept a `--output folder` in which the files will be put.

It can also be put in the configure block.

Hope this helps

**Comment by MaxLap** [comment]
I realized afterward that we are talking about takeover specifically. So I looked around some more and here is a more complete answer. 

If you use takeover with SimpleCov, the whole reporting it done by SimpleCov (including where things go). DeepCover basically only changes the coverage lines that SimpleCov receives, the rest is up to SimpleCov.

However, the lines we pass to SimpleCov will have some forced to 0 visits based on branch coverage. This can be disabled with the option `allow_partial true`. This doesn't work right now due to a bug, which will be fixed in the next release. We are having issues on the CI, so I need to solve that before doing the release.

I understand you also want to have the full branch coverage report that DeepCover. Having both at the same time is not a usecase we have considered, but it may be possible. If you call your tests which use both takeover and SimpleCov by prefixing the command with `deep-cover exec`, it is possible that our own report will also be generated. (I didn't test this, but its a possible outcome)

So to reformulate: Wait until 0.7.6, I will tell you here when it is released.
Have a .deep_cover.rb file
```
DeepCover.configure do
  # Set directory for the output of deep-cover's report
  output 'This/is_my/directory'
  # This makes the line coverage ignore branch coverage
  allow_partial true
end
```

Then, run your tests this way: `deep-cover exec command to run tests`

**Comment by MaxLap** [comment]
I just release 0.7.6. So try it out and let us know

**Comment by zs787** [comment]
> I just released 0.7.6. So try it out and let us know

Thank you @MaxLap ! I will spend some time on it this week and let you know how it goes.

**Comment by zs787** [comment]
@MaxLap sorry for the late response as I just had the chance to test things out using 0.7.6, and here is what I found:

**Scenario 1** (using deep-cover without taking over, just by running `deep-cover exec rspec`)

1. output unfortunaltey didn't work, for some reason no matter what I do the report ends up under `coverage/` i.e. `HTML generated: open ./coverage/index.html`

2. Why `deep-cover` creates a copy of the paths being covered under coverage i.e. `coverage/my_app/app` &  `coverage/my_app/lib`

3. Report by deep-cover generated successfully.

**Scenario 2** (using deep-cover with take-over, and setting `allow_partial true` and use `deep-cover exec` )

1. Same as point number 1 above 
2. Same as point number 2 above
3. I'm not really sure the `.deep_cover.rb` is working from the tests I have run so far.
4. the overall way of doing this scenario does not seem working while having simple-cov and the takeover option `RuntimeError:
  cannot change the measuring target during coverage measurement`

I think for the time being what we will do is simply add deep-cover without the take over option, and run it optionally. I don't know the if the output path is being affected by anything else on my side, but I assume its working for you.

So the fact that the report location is not working/changing we may just go with the option to have deep-cover run optionally outside the pipeline to get some insight of out branch coverage.

What would be the way to include or exclude paths that we need or don't need covered in the configuration ?

let me know if you require further information on this.

**Comment by MaxLap** [comment]
Sorry, i was away in vacation. I will take a look, but at this this week. From a quick look, it seems that you are right that the report location is not working, we will have to investigate.

**Comment by marcandre** [comment]
And I should have updated this ticket, sorry.

If you specify options with the CLI, they should be taken into account, but it looks like not giving options to the CLI is equivalent to giving them with the default options so they will override things in the config file, sorry about that. I opened #62 for this.

> Why deep-cover creates a copy of the paths being covered under coverage i.e. coverage/my_app/app & coverage/my_app/lib

This is normal behavior. The HTML generator's output consists of an `index.html` file and all the source files re-written in html with annotations. Those files are put in the same hierarchy as the sources.

**Comment by marcandre** [comment]
The latest release deals with CLI options correctly
