### ISSUE TITLE
How to exclude a path from coverage

### ISSUE THREAD

**Issue by stripedpumpkin** [deep-cover/deep-cover#56]
Hello. I have a Rails app with template ruby files in `lib/generators/service/templates/` that are not meant to be covered by the tests. Is there an easy way to exclude them from coverage?

**Comment by marcandre** [comment]
Good point. It's a feature we really should have. I should be able to add it pretty quickly.

**Comment by marcandre** [comment]
Sorry I didn't get around to it yet. Hopefully today or tomorrow.

**Comment by marcandre** [comment]
Status: I have something working in a branch, but I'd like it to be able to specify rooted regexp like `/^fixtures/` and those don't work yet.

**Comment by starpeak** [comment]
Thanks for your work. But it seems the branch did not get developed any longer - are there any news on how to exclude files?

**Comment by marcandre** [comment]
I've pushed and released what I had don, I hope it works well for you.

**Comment by mojavelinux** [comment]
A huge thank you for adding this feature. I can finally excluded the generated code in my project. :tada:

**Comment by stripedpumpkin** [comment]
Thanks for adding the feature!

**Comment by marcandre** [comment]
😃
