### ISSUE TITLE
`SimpleCov failed with exit 2`

### ISSUE THREAD

**Issue by k1r8r0wn** [deep-cover/deep-cover#57]
What might happened?

```
Coverage (0.00%) is below the expected minimum coverage (100.00%).
SimpleCov failed with exit 2
```

--

ruby ‘2.6.2’
deep-cover (0.7.5)
simplecov (0.17.0)

The previous version 0.5.2 was okay, after 0.6.0 I’m getting this…

**Comment by marcandre** [comment]
I'm sorry you're having issues. 0.6.0 is more than a year old and there have been 10 releases since, including 0.6.1 that was made the next day. Could you please update to 0.7.5 and report if you still have the issue?

**Comment by k1r8r0wn** [comment]
> I'm sorry you're having issues. 0.6.0 is more than a year old and there have been 10 releases since, including 0.6.1 that was made the next day. Could you please update to 0.7.5 and report if you still have the issue?

I'm already updated to 0.7.5 and have this error (even after 0.6.0)

**Comment by MaxLap** [comment]
Never saw this issue. Did you manage to solve the issue? Without any way to reproduce, we relaly have no way to help you

**Comment by MaxLap** [comment]
Closing this. Sorry for your issue. Let us know if you can provide more information

**Comment by k1r8r0wn** [comment]
I figured out the issue - it was just not full coverage & wrong line coverage output. Thanks for everyone!

**Comment by hanwenzhang123** [comment]
> 

How did you fix the SimpleCov failed with exit 2?
