### ISSUE TITLE
Does DeepCover report coverage for code in ERB templates?

### ISSUE THREAD

**Issue by mscottford** [deep-cover/deep-cover#61]
I'm curious if DeepCover is able to report on the coverage of code that is embedded in ERB templates. I read the README in detail and skimmed through the code, but I don't see any information about that.

**Comment by marcandre** [comment]
This would indeed be awesome (and ideally not just ERB but also SLIM/HAML)
I included this in our [roadmap](https://github.com/deep-cover/deep-cover/wiki/Road-Map) but we haven't worked on that.
