### ISSUE TITLE
Support Ruby 2.6 endless ranges

### ISSUE THREAD

**Issue by cboos** [deep-cover/deep-cover#63]
Just noticed that the `array[1..]` syntax of Ruby 2.6 is not supported.

```
#<TypeError: Invalid children types for DeepCover::Node::Range(type: irange): [[nil, DeepCover::Node]]>
```

With:

```
$ deep-cover --version
deep-cover version 0.7.6
```

And thanks by the way for this wonderful tool! I used to say that I had a bug per line of code not covered, now I can say that this is rather one bug per branch not covered ;-)

**Comment by marcandre** [comment]
Good catch, thanks!

Fixed & released.
