### ISSUE TITLE
Dependency on parser < 2.7 blocks modern Rubocop

### ISSUE THREAD

**Issue by slonopotamus** [deep-cover/deep-cover#67]
I cannot use both latest deep-cover-core together with latest Rubocop in my Gemfile:

```
Bundler could not find compatible versions for gem "parser":
  In Gemfile:
    deep-cover-core (~> 0.7.9) was resolved to 0.7.9, which depends on
      parser (>= 2.5, < 2.7)

    rubocop (~> 0.81.0) was resolved to 0.81.0, which depends on
      parser (>= 2.7.0.1)
```

Similar story was already in the past: #55.

**Comment by marcandre** [comment]
Sorry about this, it was silly of me to put a maximum version, especially since `parser` doesn't use semantic versioning and even '3.0' will be compatible.

Fixed and released.
