### ISSUE TITLE
Rails autoloading of module

### ISSUE THREAD

**Issue by marcandre** [deep-cover/deep-cover#8]
@MaxLap: Did you have a chance to check that Rails' autoloading of classes still work after a takeover? From #6, looks like it no longer works.

**Comment by MaxLap** [comment]
Completely forgot about Rails' autoloading system... No, i didn't test it out with takeover. Will look into it tonight or this weekend.

**Comment by MaxLap** [comment]
@ragesoss I have been unable to reproduce your issue. Using a basic rails 5.1 application, with ruby 2.3.4, the autoload seems to work fine for both minitest and rspec.

I did find other bugs in my quest to reproduce this, so it is also possible that those bugfixes would have solved your issue. So I suggest you try with the latest version (0.1.11), if that still doesn't work, there is nothing I can do without a reproducible case. Here is my suggestion for providing us that:

I added a new spec to our test suite. It's a very basic rails 5.1 project. You can fork deep-cover and go in `deep-cover/spec/full_usage/rails51_project`. Do all the changes you need to reproduce your issue there. (you can use `rake test` / `rspec` in there) When you can reproduce so, answer here with a link to your commit on your fork and then I will be able to investigate.

If you prefer, you can also provide me a a project of your own that has this issue.

Sorry for the inconvenience and thank you for the feedback

**Comment by ragesoss** [comment]
@MaxLap the latest version seems to have done the trick! My test suite is running now.

I'll post the debug info I'm getting in another issue.

**Comment by MaxLap** [comment]
Great news! Thank ou
