### ISSUE TITLE
Our require must respect the "coding" magic comment

### ISSUE THREAD

**Issue by marcandre** [deep-cover/deep-cover#9]
```
ruby -e "require 'deep_cover/builtin_takeover'; Coverage.start; require 'rexml/source'"
```

`parser` fails because the file is interpreted as utf-8 when it's US-ascii.

**Comment by MaxLap** [comment]
@ragesoss Could you tell me which rails/ruby version you are using to reproduce the last problem in #6 so I can focus on getting that fixed asap?

**Comment by ragesoss** [comment]
@MaxLap it's ruby 2.3.1, rails 5.1.4.

**Comment by marcandre** [comment]
So, turns out we respect it, but there's a limitation with `parser` and badly written libs 'rexml' included: https://github.com/whitequark/parser#invalid-characters-inside-comments-and-literals

We now ignore gracefully these files and require them without instrumentation.

In any case, the plan is to *not* instrument other gems pretty soon, so this won't be an issue.

Released.
